// apps/desktop/src/renderer/ui/FacetChip.svelte
<!-- Shared gallery/filter facet (AI-IMP-299): one full-pill geometry,
     with an accent toggle form and the kit's removable tag form. -->
<script lang="ts">
  import { tooltip } from '../chrome/tooltip'

  let {
    label,
    active = false,
    testid,
    disabled = false,
    onToggle,
    onRemove,
    removeLabel,
  }: {
    label: string
    active?: boolean
    testid?: string
    disabled?: boolean
    onToggle?: () => void
    onRemove?: () => void
    removeLabel?: string
  } = $props()
</script>

{#if onRemove}
  <span class="facet removable" data-testid={testid}>
    {label}
    <button
      type="button"
      aria-label={removeLabel ?? `Remove ${label}`}
      onclick={onRemove}
      use:tooltip={{ name: removeLabel ?? `Remove ${label}` }}
    >✕</button>
  </span>
{:else}
  <button
    type="button"
    class="facet toggle"
    data-testid={testid}
    aria-pressed={active}
    {disabled}
    onclick={onToggle}
  >
    {label}
  </button>
{/if}

<style>
  .facet {
    border: 1px solid var(--ew-border-strong);
    border-radius: 999px;
    background: var(--ew-surface-raised);
    color: var(--ew-text-muted);
    font: inherit;
    font-size: 0.78rem;
  }

  .toggle {
    padding: 0.18rem 0.6rem;
    cursor: pointer;
  }

  .toggle[aria-pressed='true'] {
    border-color: var(--ew-accent);
    background: var(--ew-accent);
    color: var(--ew-on-accent);
  }

  .removable {
    display: inline-flex;
    align-items: center;
    gap: 0.25rem;
    padding: 0.14rem 0.3rem 0.14rem 0.55rem;
    color: var(--ew-text);
  }

  .removable button {
    padding: 0 0.15rem;
    border: 0;
    background: transparent;
    color: var(--ew-text-muted);
    font: inherit;
    font-size: 0.7rem;
    cursor: pointer;
  }

  button:hover:not(:disabled) {
    color: var(--ew-text);
  }

  button:focus-visible {
    outline: 2px solid var(--ew-focus-ring);
    outline-offset: 1px;
  }

  button:disabled {
    opacity: 0.4;
    cursor: default;
  }
</style>

// RAG/design/archive/Design guidelines and hero images/uploads/Expanding Worlds Design System/components/controls/FacetChip.jsx
import React from 'react';

/** Facet/filter chip (gallery facet bar, graph filters): full pill,
 * raised at rest, accent when on; tag facets use the active-tag form
 * with a ✕. */
export function FacetChip({ label, on, tag, onToggle, onClear, style }) {
  if (tag)
    return (
      <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.25rem', padding: '0.14rem 0.3rem 0.14rem 0.55rem', background: 'var(--ew-surface-raised)', border: '1px solid var(--ew-border-strong)', borderRadius: 999, fontSize: '0.78rem', color: 'var(--ew-text)', fontFamily: 'var(--ew-font-ui)', ...style }}>
        {label}
        <button type="button" onClick={onClear} style={{ padding: '0 0.15rem', background: 'transparent', border: 'none', color: 'var(--ew-text-muted)', fontSize: '0.7rem', cursor: 'pointer' }}>✕</button>
      </span>
    );
  return (
    <button
      type="button"
      onClick={onToggle}
      style={{
        padding: '0.18rem 0.6rem',
        fontSize: '0.78rem',
        fontFamily: 'var(--ew-font-ui)',
        background: on ? 'var(--ew-accent)' : 'var(--ew-surface-raised)',
        color: on ? 'var(--ew-on-accent)' : 'var(--ew-text-muted)',
        border: `1px solid ${on ? 'var(--ew-accent)' : 'var(--ew-border-strong)'}`,
        borderRadius: 999,
        cursor: 'pointer',
        ...style,
      }}
    >
      {label}
    </button>
  );
}
