// RAG/design/archive/Design guidelines and hero images/design-system/components/controls/Segmented.jsx
import React from 'react';

/** Segmented pill control (gallery facets, source-panel tag-border
 * toggle): full-pill outer border, on-segment = accent fill. */
export function Segmented({ options = [], value, onChange, style }) {
  return (
    <span style={{ display: 'inline-flex', border: '1px solid var(--ew-border-strong)', borderRadius: 999, overflow: 'hidden', ...style }}>
      {options.map((opt, i) => (
        <button
          key={opt}
          type="button"
          onClick={onChange ? () => onChange(opt) : undefined}
          style={{
            padding: '0.2rem 0.65rem',
            fontSize: '0.78rem',
            fontFamily: 'var(--ew-font-ui)',
            background: value === opt ? 'var(--ew-accent)' : 'transparent',
            color: value === opt ? 'var(--ew-on-accent)' : 'var(--ew-text-muted)',
            border: 'none',
            borderLeft: i > 0 ? '1px solid var(--ew-border)' : 'none',
            cursor: 'pointer',
          }}
        >
          {opt}
        </button>
      ))}
    </span>
  );
}

// apps/desktop/src/renderer/ui/Segmented.svelte
<!-- Shared kit segmented control (AI-IMP-299). The primitive owns the
     full-pill geometry, focus, and selected palette; callers own only
     option identity and surrounding layout. -->
<script lang="ts">
  export interface SegmentedOption {
    value: string
    label: string
    testid?: string
    disabled?: boolean
  }

  let {
    options,
    value,
    ariaLabel,
    onchange,
    testid,
  }: {
    options: readonly SegmentedOption[]
    value: string
    ariaLabel: string
    onchange: (value: string) => void
    testid?: string
  } = $props()
</script>

<span class="segmented" role="group" aria-label={ariaLabel} data-testid={testid}>
  {#each options as option (option.value)}
    <button
      type="button"
      data-testid={option.testid}
      aria-pressed={value === option.value}
      disabled={option.disabled}
      onclick={() => onchange(option.value)}
    >
      {option.label}
    </button>
  {/each}
</span>

<style>
  .segmented {
    display: inline-flex;
    border: 1px solid var(--ew-border-strong);
    border-radius: 999px;
    overflow: hidden;
  }

  button {
    padding: 0.2rem 0.65rem;
    border: 0;
    background: transparent;
    color: var(--ew-text-muted);
    font: inherit;
    font-size: 0.78rem;
    cursor: pointer;
  }

  button + button {
    border-left: 1px solid var(--ew-border);
  }

  button[aria-pressed='true'] {
    background: var(--ew-accent);
    color: var(--ew-on-accent);
  }

  button:focus-visible {
    outline: 2px solid var(--ew-focus-ring);
    outline-offset: -2px;
  }

  button:disabled {
    opacity: 0.4;
    cursor: default;
  }

</style>
